import type { SafariData } from "@/features/safari";
import {
  RESORT_INCLUSION_WITH_CAB,
  RESORT_TO_DHANGARI,
  RESORT_TO_RAMNAGAR,
  CONTACT_CALL_TEXT,
} from "@/shared/constants/ui.constants";

export const safariData: SafariData = {
  header: {
    parkTitle: "Jim Corbett National Park",
    tagline: "Right place to experience thrill, adventure, craziness & wildlife",
    callText: CONTACT_CALL_TEXT,
    coreZones: ["Dhikala", "Durga Devi", "Garjiya", "Bijrani", "Dhela", "Jhirna"],
    bufferZones: ["Sitawani", "Bhandarpani", "Pawalgarh", "Hathidanger", "Phato"],
  },
  indian: [
    {
      id: "core-current-indian",
      category: "current",
      title: "Core Zone- INDIAN CURRENT SAFARI (Within 4 Days)",
      tables: [
        {
          inclusionText: RESORT_INCLUSION_WITH_CAB,
          rateRows: [
            {
              zone: "Durga Devi Zone",
              zoneType: "core",
              rate: 13200,
              gstRate: 13860,
              timing: { morning: "4:30 to 10:00 AM", afternoon: "1:30 to 7:30 PM" },
              distanceFromRamnagar: "27 Km | 1 Hour",
            },
            {
              zone: "Dhela Zone",
              zoneType: "core",
              rate: 13200,
              gstRate: 13860,
              timing: { morning: "4:30 to 10:00 AM", afternoon: "1:30 to 7:30 PM" },
              distanceFromRamnagar: "27 Km | 1 Hour",
            },
            {
              zone: "Jhirna Zone",
              zoneType: "core",
              rate: 13200,
              gstRate: 13860,
              timing: { morning: "4:30 to 10:00 AM", afternoon: "1:30 to 7:30 PM" },
              distanceFromRamnagar: "27 Km | 1 Hour",
            },
            {
              zone: "Garjiya Zone",
              zoneType: "core",
              rate: 13200,
              gstRate: 13860,
              timing: { morning: "4:30 to 10:00 AM", afternoon: "1:30 to 7:30 PM" },
              distanceFromRamnagar: "27 Km | 1 Hour",
            },
            {
              zone: "Bijrani Zone",
              zoneType: "core",
              rate: 13200,
              gstRate: 13860,
              timing: { morning: "4:30 to 10:00 AM", afternoon: "1:30 to 7:30 PM" },
              distanceFromRamnagar: "27 Km | 1 Hour",
            },
          ],
        },
        {
          inclusionText: "Include: Gypsy, Guide, Permit, Pickup & Drop Safari Gate",
          rateRows: [
            {
              zone: "Durga Devi Zone",
              zoneType: "core",
              rate: 9100,
              gstRate: 9555,
              timing: { morning: "5:30 to 9:00 AM", afternoon: "2:30 to 6:30 PM" },
              distanceFromRamnagar: "54 Km | 2 Hours",
            },
            {
              zone: "Dhela Zone",
              zoneType: "core",
              rate: 9100,
              gstRate: 9555,
              timing: { morning: "5:30 to 9:00 AM", afternoon: "2:30 to 6:30 PM" },
              distanceFromRamnagar: "41 Km | 1.30 Hours",
            },
            {
              zone: "Jhirna Zone",
              zoneType: "core",
              rate: 9100,
              gstRate: 9555,
              timing: { morning: "5:30 to 9:00 AM", afternoon: "2:30 to 6:30 PM" },
              distanceFromRamnagar: "41 Km | 1.30 Hours",
            },
            {
              zone: "Garjiya Zone",
              zoneType: "core",
              rate: 9100,
              gstRate: 9555,
              timing: { morning: "5:30 to 9:00 AM", afternoon: "2:30 to 6:30 PM" },
              distanceFromRamnagar: "31 Km | 1 Hour",
            },
            {
              zone: "Bijrani Zone",
              zoneType: "core",
              rate: 9100,
              gstRate: 9555,
              timing: { morning: "5:30 to 9:00 AM", afternoon: "2:30 to 6:30 PM" },
              distanceFromRamnagar: "28 Km | 1 Hour",
            },
          ],
        },
      ],
    },
    {
      id: "core-prebooking-indian",
      category: "prebooking",
      title: "Core Zone- INDIAN PRE-BOOKING SAFARI DETAILS",
      tables: [
        {
          inclusionText: RESORT_INCLUSION_WITH_CAB,
          rateRows: [
            {
              zone: "Bijrani Zone",
              zoneType: "core",
              rate: 12200,
              gstRate: 12810,
              timing: { morning: "4:30 to 10:00 AM", afternoon: "1:30 to 7:30 PM" },
              distanceFromRamnagar: "27 Km | 1 Hour",
            },
            {
              zone: "Dhela Zone",
              zoneType: "core",
              rate: 12200,
              gstRate: 12810,
              timing: { morning: "4:30 to 10:00 AM", afternoon: "1:30 to 7:30 PM" },
              distanceFromRamnagar: "27 Km | 1 Hour",
            },
            {
              zone: "Jhirna Zone",
              zoneType: "core",
              rate: 12200,
              gstRate: 12810,
              timing: { morning: "4:30 to 10:00 AM", afternoon: "1:30 to 7:30 PM" },
              distanceFromRamnagar: "27 Km | 1 Hour",
            },
            {
              zone: "Garjiya Zone",
              zoneType: "core",
              rate: 12200,
              gstRate: 12810,
              timing: { morning: "4:30 to 10:00 AM", afternoon: "1:30 to 7:30 PM" },
              distanceFromRamnagar: "27 Km | 1 Hour",
            },
            {
              zone: "Durga Devi Zone",
              zoneType: "core",
              rate: 12200,
              gstRate: 12810,
              timing: { morning: "4:30 to 10:00 AM", afternoon: "1:30 to 7:30 PM" },
              distanceFromRamnagar: "27 Km | 1 Hour",
            },
          ],
        },
        {
          inclusionText: "Include: Gypsy, Guide, Permit, Pickup & Drop Safari Gate",
          rateRows: [
            {
              zone: "Bijrani Zone",
              zoneType: "core",
              rate: 8100,
              gstRate: 8505,
              timing: { morning: "5:30 to 10:00 AM", afternoon: "2:30 to 6:30 PM" },
              distanceFromRamnagar: "28 Km | 1 Hour",
            },
            {
              zone: "Dhela Zone",
              zoneType: "core",
              rate: 8100,
              gstRate: 8505,
              timing: { morning: "5:30 to 10:00 AM", afternoon: "2:30 to 6:30 PM" },
              distanceFromRamnagar: "41 Km | 1.30 Hours",
            },
            {
              zone: "Jhirna Zone",
              zoneType: "core",
              rate: 8100,
              gstRate: 8505,
              timing: { morning: "5:30 to 10:00 AM", afternoon: "2:30 to 6:30 PM" },
              distanceFromRamnagar: "41 Km | 1.30 Hours",
            },
            {
              zone: "Garjiya Zone",
              zoneType: "core",
              rate: 8100,
              gstRate: 8505,
              timing: { morning: "5:30 to 10:00 AM", afternoon: "2:30 to 6:30 PM" },
              distanceFromRamnagar: "31 Km | 1 Hour",
            },
            {
              zone: "Durga Devi Zone",
              zoneType: "core",
              rate: 8100,
              gstRate: 8505,
              timing: { morning: "5:30 to 10:00 AM", afternoon: "2:30 to 6:30 PM" },
              distanceFromRamnagar: "54 Km | 2 Hours",
            },
          ],
        },
      ],
      warning: "Late entries will NOT be adjusted in any other schedule (No return, no refund, no exchange).",
    },
    {
      id: "buffer-indian",
      category: "combined",
      title: "Buffer Zone- INDIAN PRE-BOOKING & CURRENT SAFARI",
      tables: [
        {
          inclusionText: RESORT_INCLUSION_WITH_CAB,
          rateRows: [
            {
              zone: "Sitawani Zone",
              zoneType: "buffer",
              rate: 9800,
              gstRate: 10290,
              timing: { morning: "4:30 to 10:00 AM", afternoon: "1:30 to 7:30 PM" },
              distanceFromRamnagar: "27 Km | 1 Hour",
            },
            {
              zone: "Bhandarpani Zone",
              zoneType: "buffer",
              rate: 9800,
              gstRate: 10290,
              timing: { morning: "4:30 to 10:00 AM", afternoon: "1:30 to 7:30 PM" },
              distanceFromRamnagar: "27 Km | 1 Hour",
            },
            {
              zone: "Pawalgarh Zone",
              zoneType: "buffer",
              rate: 9800,
              gstRate: 10290,
              timing: { morning: "4:30 to 10:00 AM", afternoon: "1:30 to 7:30 PM" },
              distanceFromRamnagar: "27 Km | 1 Hour",
            },
            {
              zone: "Hathidanger Zone",
              zoneType: "buffer",
              rate: 9800,
              gstRate: 10290,
              timing: { morning: "4:30 to 10:00 AM", afternoon: "1:30 to 7:30 PM" },
              distanceFromRamnagar: "27 Km | 1 Hour",
            },
            {
              zone: "Phato Zone",
              zoneType: "buffer",
              rate: 9800,
              gstRate: 10290,
              timing: { morning: "4:30 to 10:00 AM", afternoon: "1:30 to 7:30 PM" },
              distanceFromRamnagar: "27 Km | 1 Hour",
            },
          ],
        },
        {
          inclusionText: "Include: Gypsy, Guide, Permit, Pickup & Drop Safari Gate",
          rateRows: [
            {
              zone: "Sitawani Zone",
              zoneType: "buffer",
              rate: 6400,
              gstRate: 6720,
              timing: { morning: "5:30 to 9:00 AM", afternoon: "2:30 to 6:30 PM" },
              distanceFromRamnagar: "27 Km | 1 Hour",
            },
            {
              zone: "Bhandarpani Zone",
              zoneType: "buffer",
              rate: 6400,
              gstRate: 6720,
              timing: { morning: "5:30 to 9:00 AM", afternoon: "2:30 to 6:30 PM" },
              distanceFromRamnagar: "27 Km | 1 Hour",
            },
            {
              zone: "Pawalgarh Zone",
              zoneType: "buffer",
              rate: 6400,
              gstRate: 6720,
              timing: { morning: "5:30 to 9:00 AM", afternoon: "2:30 to 6:30 PM" },
              distanceFromRamnagar: "27 Km | 1 Hour",
            },
            {
              zone: "Hathidanger Zone",
              zoneType: "buffer",
              rate: 6700,
              gstRate: 7035,
              timing: { morning: "5:30 to 9:00 AM", afternoon: "2:30 to 6:30 PM" },
              distanceFromRamnagar: "27 Km | 1 Hour",
            },
            {
              zone: "Phato Zone",
              zoneType: "buffer",
              rate: 6700,
              gstRate: 7035,
              timing: { morning: "5:30 to 9:00 AM", afternoon: "2:30 to 6:30 PM" },
              distanceFromRamnagar: "27 Km | 1 Hour",
            },
          ],
        },
      ],
      warning: "Late entries will NOT be adjusted in any other schedule (No return, no refund, no exchange).",
    },
    {
      id: "dhikala-indian",
      category: "combined",
      title: "Dhikala Zone Canter Safari (Day Visit)",
      subtitle: "INDIAN PRE-BOOKING & CURRENT SAFARI",
      tables: [
        {
          inclusionText: "Include: Jeep, Guide, Permit, Pickup & Drop from Ramnagar",
          rateRows: [
            {
              zone: "Dhikala Zone",
              zoneType: "core",
              rate: 3260,
              gstRate: 3423,
              timing: { morning: "5:30 to 11:30 AM", afternoon: "12:30 to 7:00 PM" },
              distanceFromRamnagar: "27 Km | 1 Hour",
            },
          ],
        },
      ],
      warning: "Late entries will NOT be adjusted in any other schedule (No return, no refund, no exchange).",
      cabTables: [
        {
          rateRows: [
            {
              location: RESORT_TO_RAMNAGAR,
              pickupDrop: "Round Trip",
              dzire: 3100,
              ertiga: 4200,
              innovaCrysta: 6500,
            },
            {
              location: RESORT_TO_DHANGARI,
              pickupDrop: "Round Trip",
              dzire: 5200,
              ertiga: 6500,
              innovaCrysta: 7800,
            },
          ],
        },
      ],
      notes: [
        "In case of no-show on the given time, the tickets will be considered canceled and no refunds would be provided for it.",
      ],
    },
  ],
  foreigner: [
    {
      id: "core-current-foreigner",
      category: "current",
      title: "Core Zone- FOREIGNER CURRENT SAFARI (Within 4 Days)",
      tables: [
        {
          inclusionText: RESORT_INCLUSION_WITH_CAB,
          rateRows: [
            {
              zone: "Bijrani Zone",
              zoneType: "core",
              rate: 17800,
              gstRate: 18690,
              timing: { morning: "4:30 to 10:00 AM", afternoon: "1:30 to 7:30 PM" },
              distanceFromRamnagar: "27 Km | 1 Hour",
            },
            {
              zone: "Dhela Zone",
              zoneType: "core",
              rate: 17800,
              gstRate: 18690,
              timing: { morning: "4:30 to 10:00 AM", afternoon: "1:30 to 7:30 PM" },
              distanceFromRamnagar: "27 Km | 1 Hour",
            },
            {
              zone: "Jhirna Zone",
              zoneType: "core",
              rate: 17800,
              gstRate: 18690,
              timing: { morning: "4:30 to 10:00 AM", afternoon: "1:30 to 7:30 PM" },
              distanceFromRamnagar: "27 Km | 1 Hour",
            },
            {
              zone: "Garjiya Zone",
              zoneType: "core",
              rate: 17800,
              gstRate: 18690,
              timing: { morning: "4:30 to 10:00 AM", afternoon: "1:30 to 7:30 PM" },
              distanceFromRamnagar: "27 Km | 1 Hour",
            },
            {
              zone: "Durga Devi Zone",
              zoneType: "core",
              rate: 17800,
              gstRate: 18690,
              timing: { morning: "4:30 to 10:00 AM", afternoon: "1:30 to 7:30 PM" },
              distanceFromRamnagar: "27 Km | 1 Hour",
            },
          ],
        },
        {
          inclusionText: "Include: Gypsy, Guide, Permit, Pickup & Drop Safari Gate",
          rateRows: [
            {
              zone: "Bijrani Zone",
              zoneType: "core",
              rate: 13800,
              gstRate: 14490,
              timing: { morning: "5:30 to 9:00 AM", afternoon: "2:30 to 6:30 PM" },
              distanceFromRamnagar: "28 Km | 1 Hour",
            },
            {
              zone: "Dhela Zone",
              zoneType: "core",
              rate: 13800,
              gstRate: 14490,
              timing: { morning: "5:30 to 9:00 AM", afternoon: "2:30 to 6:30 PM" },
              distanceFromRamnagar: "41 Km | 1.30 Hours",
            },
            {
              zone: "Jhirna Zone",
              zoneType: "core",
              rate: 13800,
              gstRate: 14490,
              timing: { morning: "5:30 to 9:00 AM", afternoon: "2:30 to 6:30 PM" },
              distanceFromRamnagar: "41 Km | 1.30 Hours",
            },
            {
              zone: "Garjiya Zone",
              zoneType: "core",
              rate: 13800,
              gstRate: 14490,
              timing: { morning: "5:30 to 9:00 AM", afternoon: "2:30 to 6:30 PM" },
              distanceFromRamnagar: "31 Km | 1 Hour",
            },
            {
              zone: "Durga Devi Zone",
              zoneType: "core",
              rate: 13800,
              gstRate: 14490,
              timing: { morning: "5:30 to 9:00 AM", afternoon: "2:30 to 6:30 PM" },
              distanceFromRamnagar: "54 Km | 2 Hours",
            },
          ],
        },
      ],
    },
    {
      id: "core-prebooking-foreigner",
      category: "prebooking",
      title: "Core Zone- FOREIGNER PRE-BOOKING SAFARI DETAILS",
      tables: [
        {
          inclusionText: RESORT_INCLUSION_WITH_CAB,
          rateRows: [
            {
              zone: "Bijrani Zone",
              zoneType: "core",
              rate: 16700,
              gstRate: 17535,
              timing: { morning: "4:30 to 10:00 AM", afternoon: "1:30 to 7:30 PM" },
              distanceFromRamnagar: "27 Km | 1 Hour",
            },
            {
              zone: "Dhela Zone",
              zoneType: "core",
              rate: 16700,
              gstRate: 17535,
              timing: { morning: "4:30 to 10:00 AM", afternoon: "1:30 to 7:30 PM" },
              distanceFromRamnagar: "27 Km | 1 Hour",
            },
            {
              zone: "Jhirna Zone",
              zoneType: "core",
              rate: 16700,
              gstRate: 17535,
              timing: { morning: "4:30 to 10:00 AM", afternoon: "1:30 to 7:30 PM" },
              distanceFromRamnagar: "27 Km | 1 Hour",
            },
            {
              zone: "Garjiya Zone",
              zoneType: "core",
              rate: 16700,
              gstRate: 17535,
              timing: { morning: "4:30 to 10:00 AM", afternoon: "1:30 to 7:30 PM" },
              distanceFromRamnagar: "27 Km | 1 Hour",
            },
            {
              zone: "Durga Devi Zone",
              zoneType: "core",
              rate: 16700,
              gstRate: 17535,
              timing: { morning: "4:30 to 10:00 AM", afternoon: "1:30 to 7:30 PM" },
              distanceFromRamnagar: "27 Km | 1 Hour",
            },
          ],
        },
        {
          inclusionText: "Include: Gypsy, Guide, Permit, Pickup & Drop Safari Gate",
          rateRows: [
            {
              zone: "Bijrani Zone",
              zoneType: "core",
              rate: 12700,
              gstRate: 13335,
              timing: { morning: "6:00 to 10:00 AM", afternoon: "2:30 to 6:30 PM" },
              distanceFromRamnagar: "28 Km | 1 Hour",
            },
            {
              zone: "Dhela Zone",
              zoneType: "core",
              rate: 12700,
              gstRate: 13335,
              timing: { morning: "6:00 to 10:00 AM", afternoon: "2:30 to 6:30 PM" },
              distanceFromRamnagar: "41 Km | 1.30 Hours",
            },
            {
              zone: "Jhirna Zone",
              zoneType: "core",
              rate: 12700,
              gstRate: 13335,
              timing: { morning: "6:00 to 10:00 AM", afternoon: "2:30 to 6:30 PM" },
              distanceFromRamnagar: "41 Km | 1.30 Hours",
            },
            {
              zone: "Garjiya Zone",
              zoneType: "core",
              rate: 12700,
              gstRate: 13335,
              timing: { morning: "6:00 to 10:00 AM", afternoon: "2:30 to 6:30 PM" },
              distanceFromRamnagar: "31 Km | 1 Hour",
            },
            {
              zone: "Durga Devi Zone",
              zoneType: "core",
              rate: 12700,
              gstRate: 13335,
              timing: { morning: "6:00 to 10:00 AM", afternoon: "2:30 to 6:30 PM" },
              distanceFromRamnagar: "54 Km | 2 Hours",
            },
          ],
        },
      ],
      warning: "Late entries will NOT be adjusted in any other schedule (No return, no refund, no exchange).",
    },
    {
      id: "buffer-foreigner",
      category: "combined",
      title: "Buffer Zone- FOREIGNER PRE-BOOKING & CURRENT SAFARI",
      tables: [
        {
          inclusionText: RESORT_INCLUSION_WITH_CAB,
          rateRows: [
            {
              zone: "Sitawani Zone",
              zoneType: "buffer",
              rate: 13200,
              gstRate: 13860,
              timing: { morning: "4:30 to 10:00 AM", afternoon: "1:30 to 7:30 PM" },
              distanceFromRamnagar: "27 Km | 1 Hour",
            },
            {
              zone: "Bhandarpani Zone",
              zoneType: "buffer",
              rate: 13200,
              gstRate: 13860,
              timing: { morning: "4:30 to 10:00 AM", afternoon: "1:30 to 7:30 PM" },
              distanceFromRamnagar: "27 Km | 1 Hour",
            },
            {
              zone: "Pawalgarh Zone",
              zoneType: "buffer",
              rate: 13200,
              gstRate: 13860,
              timing: { morning: "4:30 to 10:00 AM", afternoon: "1:30 to 7:30 PM" },
              distanceFromRamnagar: "27 Km | 1 Hour",
            },
            {
              zone: "Hathidanger Zone",
              zoneType: "buffer",
              rate: 14200,
              gstRate: 14910,
              timing: { morning: "4:30 to 10:00 AM", afternoon: "1:30 to 7:30 PM" },
              distanceFromRamnagar: "27 Km | 1 Hour",
            },
            {
              zone: "Phato Zone",
              zoneType: "buffer",
              rate: 14200,
              gstRate: 14910,
              timing: { morning: "4:30 to 10:00 AM", afternoon: "1:30 to 7:30 PM" },
              distanceFromRamnagar: "27 Km | 1 Hour",
            },
          ],
        },
        {
          inclusionText: "Include: Gypsy, Guide, Permit, Pickup & Drop Safari Gate",
          rateRows: [
            {
              zone: "Sitawani Zone",
              zoneType: "buffer",
              rate: 9200,
              gstRate: 9660,
              timing: { morning: "5:30 to 9:00 AM", afternoon: "2:30 to 6:30 PM" },
              distanceFromRamnagar: "27 Km | 1 Hour",
            },
            {
              zone: "Bhandarpani Zone",
              zoneType: "buffer",
              rate: 9200,
              gstRate: 9660,
              timing: { morning: "5:30 to 9:00 AM", afternoon: "2:30 to 6:30 PM" },
              distanceFromRamnagar: "27 Km | 1 Hour",
            },
            {
              zone: "Pawalgarh Zone",
              zoneType: "buffer",
              rate: 9200,
              gstRate: 9660,
              timing: { morning: "5:30 to 9:00 AM", afternoon: "2:30 to 6:30 PM" },
              distanceFromRamnagar: "27 Km | 1 Hour",
            },
            {
              zone: "Hathidanger Zone",
              zoneType: "buffer",
              rate: 10300,
              gstRate: 10815,
              timing: { morning: "5:30 to 9:00 AM", afternoon: "2:30 to 6:30 PM" },
              distanceFromRamnagar: "27 Km | 1 Hour",
            },
            {
              zone: "Phato Zone",
              zoneType: "buffer",
              rate: 10300,
              gstRate: 10815,
              timing: { morning: "5:30 to 9:00 AM", afternoon: "2:30 to 6:30 PM" },
              distanceFromRamnagar: "27 Km | 1 Hour",
            },
          ],
        },
      ],
      warning: "Late entries will NOT be adjusted in any other schedule (No return, no refund, no exchange).",
    },
    {
      id: "dhikala-foreigner",
      category: "combined",
      title: "Dhikala Zone Canter Safari (Day Visit)",
      subtitle: "FOREIGNER PRE-BOOKING & CURRENT SAFARI",
      tables: [
        {
          inclusionText: "Include: Jeep, Guide, Permit, Pickup & Drop from Ramnagar",
          rateRows: [
            {
              zone: "Dhikala Zone",
              zoneType: "core",
              rate: 5000,
              gstRate: 5250,
              timing: { morning: "5:30 to 11:30 AM", afternoon: "12:30 to 7:00 PM" },
              distanceFromRamnagar: "27 Km | 1 Hour",
            },
          ],
        },
      ],
      warning: "Late entries will NOT be adjusted in any other schedule (No return, no refund, no exchange).",
      cabTables: [
        {
          rateRows: [
            {
              location: RESORT_TO_RAMNAGAR,
              pickupDrop: "Round Trip",
              dzire: 3100,
              ertiga: 4200,
              innovaCrysta: 6500,
            },
            {
              location: RESORT_TO_DHANGARI,
              pickupDrop: "Round Trip",
              dzire: 5200,
              ertiga: 6500,
              innovaCrysta: 7800,
            },
          ],
        },
      ],
      notes: [
        "In case of no-show on the given time, the tickets will be considered canceled and no refunds would be provided for it.",
      ],
    },
  ],
  policyLines: [
    "It is mandatory to pay 5% GST as per government rules.",
    "Late entries will NOT be adjusted in any other schedule (No return, no refund, no exchange).",
    "No-show at reporting time is treated as canceled and no refund is provided.",
    "Note: You can visit only one zone at a time.",
  ],
};
